# Generated by Django 2.2 on 2019-08-13 18:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DengueArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daname', models.CharField(max_length=50)),
                ('dadistrict', models.CharField(max_length=50)),
                ('dadivision', models.CharField(max_length=50)),
                ('dalat', models.FloatField()),
                ('dalon', models.FloatField()),
                ('daalert', models.CharField(max_length=100)),
                ('dacreated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'denguearea',
            },
        ),
        migrations.CreateModel(
            name='Medicals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=500)),
                ('maddress', models.CharField(max_length=500)),
                ('mdistrict', models.CharField(max_length=50)),
                ('mdivision', models.CharField(max_length=50)),
                ('mbed', models.IntegerField()),
                ('mbedfullnot', models.CharField(max_length=50)),
                ('mfree', models.CharField(max_length=50)),
                ('mpublic', models.CharField(max_length=50)),
                ('mlat', models.FloatField()),
                ('mlon', models.FloatField()),
            ],
            options={
                'db_table': 'medicals',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Newstitle', models.CharField(max_length=500)),
                ('Newsdetails', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Newsauthors', models.CharField(max_length=100)),
                ('Newswhere', models.CharField(max_length=200)),
                ('Newscreated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
