# Generated by Django 2.2 on 2019-08-14 09:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arttitle', models.CharField(max_length=500)),
                ('artdetails', ckeditor_uploader.fields.RichTextUploadingField()),
                ('artauthors', models.CharField(max_length=100)),
                ('artrefer', ckeditor_uploader.fields.RichTextUploadingField()),
                ('artcreated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='BloodDonors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdname', models.CharField(max_length=500)),
                ('bdblood', models.CharField(max_length=50)),
                ('bdavailable', models.CharField(max_length=50)),
                ('bdaddress', models.CharField(max_length=400)),
                ('bdcontact', models.CharField(max_length=400)),
                ('bdemail', models.EmailField(max_length=400)),
                ('bdgender', models.CharField(max_length=50)),
                ('bdcreated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blooddonors',
            },
        ),
        migrations.CreateModel(
            name='DoctorsAdvised',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctitle', models.CharField(max_length=500)),
                ('docdetails', ckeditor_uploader.fields.RichTextUploadingField()),
                ('docwho', models.CharField(max_length=100)),
                ('doccreated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'doctorsadvised',
            },
        ),
    ]
